stages:
  - build
  - deploy

build:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - export DOCKER_BUILDKIT=1
  script:
    - docker build -o dist .
  artifacts:
    paths:
      - dist
